version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo19_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/odoo/ODOO_19_CE/db-data:/var/lib/postgresql/data/pgdata

  web:
    image: odoo:19.0
    container_name: odoo19_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /opt/odoo/ODOO_19_CE/odoo-data:/var/lib/odoo
      - /opt/odoo/ODOO_19_CE/addons:/mnt/extra-addons
      - /opt/odoo/ODOO_19_CE/odoo-19.0/odoo.conf:/opt/odoo/odoo.conf
      - /opt/odoo/ODOO_19_CE/odoo-19.0/entrypoint.sh:/opt/odoo/entrypoint.sh
      - /opt/odoo/ODOO_19_CE/odoo-19.0/wait-for-psql.py:/opt/odoo/wait-for-psql.py
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      ODOO_RC: /opt/odoo/odoo.conf
    entrypoint: ["/opt/odoo/entrypoint.sh", "odoo"]
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
