version: '3.8'

services:
  db:
    container_name: db_instance_1
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./db-data:/var/lib/postgresql/data

  odoo:
    container_name: odoo_instance_1
    build:
      context: ./odoo-19.0
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8082:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo-19.0/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-19.0/wait-for-psql.py:/usr/local/bin/wait-for-psql.py
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
      ODOO_RC: /etc/odoo/odoo.conf
    entrypoint: ["/entrypoint.sh", "odoo"]
    restart: unless-stopped