version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo19_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

  web:
    image: odoo:19.0
    container_name: odoo19_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo-19.0:/opt/odoo
      - ./odoo-19.0/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - ODOO_RC=/etc/odoo/odoo.conf
    entrypoint: ["/opt/odoo/entrypoint.sh", "odoo"]
    secrets:
      - postgresql_password
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
